### ISSUE TITLE
Wrong data package profile - not readable by datapackage-py

### ISSUE THREAD

**Issue by larsschellhas** [Open-Power-System-Data/conventional_power_plants#13]
The Data packages for conventional power plants and national generation capacity contain a wrong (non-standard-conform) data package profile.
Currently the datapackage.json says:
`"profile": "tabular_data_package"`
but it should say
` "profile": "tabular-data-package"`
as can be found in the [standard specification](https://frictionlessdata.io/specs/tabular-data-package/#specification).

Because of this typo the package cannot be opened by the python library for data packages.

**Comment by larsschellhas** [comment]
Any update on this matter?
It´s a quick and clean fix for a small mistake, but it matters a lot, when trying to deal automatically with data packages. :)

**Comment by weibezahn** [comment]
Hi Lars, yes, this issue will be resolved with the new release!
